version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 20021231
      POSTGRES_DB: hospital
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

